import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const scale = size => (width / 375) * size;

export const theme = {
  navy: '#071b34',
  navyMid: '#0d2f58',
  blue: '#0d47a1',
  red: '#b91427',
  cream: '#fbf7f3',
  creamMid: '#f6eee6',
  cream2: '#f2e8df',
  line: '#eadbd4',
  text: '#152033',
  muted: '#687382',
  placeholder: '#a8afb8',
  paper: 'rgba(255, 255, 255, 0.86)',
  card: '#fffaf7',
  success: '#2E7D32',
  gradient: ['#fbf7f3', '#f6eee6', '#f2e8df'],
};

export const authStyles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  flex: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: scale(10),
    paddingVertical: scale(8),
    justifyContent: 'center',
  },
  screenCard: {
    width: '100%',
    maxWidth: 430,
    minHeight: scale(600),
    alignSelf: 'center',
    borderRadius: scale(32),
    borderWidth: 1,
    borderColor: 'rgba(234, 219, 212, 0.95)',
    backgroundColor: theme.card,
    overflow: 'hidden',
    shadowColor: 'rgba(7, 27, 52, 0.16)',
    shadowOffset: { width: 0, height: 22 },
    shadowOpacity: 1,
    shadowRadius: 48,
    elevation: 12,
  },
  hero: {
    paddingHorizontal: scale(20),
    paddingTop: scale(20),
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
    borderColor: theme.line,
  },
  backButtonText: {
    color: theme.navy,
    fontSize: scale(22),
    fontWeight: '400',
    lineHeight: scale(24),
    marginTop: -2,
  },
  headerTitle: {
    flex: 1,
    color: theme.text,
    fontSize: scale(20),
    fontWeight: '800',
    textAlign: 'center',
  },
  logo: {
    width: scale(128),
    height: scale(52),
  },
  panel: {
    paddingHorizontal: scale(22),
    paddingTop: scale(24),
    paddingBottom: scale(30),
  },
  eyebrow: {
    color: theme.red,
    fontSize: scale(12),
    fontWeight: '800',
    marginBottom: scale(5),
    textTransform: 'uppercase',
  },
  title: {
    color: theme.text,
    fontSize: scale(26),
    lineHeight: scale(30),
    fontWeight: '800',
    maxWidth: 330,
  },
  subheading: {
    color: theme.muted,
    fontSize: scale(14),
    lineHeight: scale(22),
    fontWeight: '500',
    marginTop: scale(8),
    marginBottom: scale(20),
    maxWidth: 340,
  },
  field: {
    marginBottom: scale(16),
  },
  label: {
    color: '#3f4754',
    fontSize: scale(12),
    fontWeight: '800',
    marginBottom: scale(5),
  },
  input: {
    height: scale(48),
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: scale(16),
    paddingHorizontal: scale(16),
    color: theme.text,
    backgroundColor: theme.paper,
    fontSize: scale(16),
    fontWeight: '600',
  },
  inputFocused: {
    borderColor: 'rgba(13, 71, 161, 0.55)',
    backgroundColor: '#fff',
  },
  otpInput: {
    fontSize: scale(24),
    fontWeight: '800',
    letterSpacing: scale(6),
    textAlign: 'center',
  },
  passwordWrap: {
    position: 'relative',
  },
  passwordInput: {
    paddingRight: scale(48),
  },
  eyeButton: {
    position: 'absolute',
    right: scale(14),
    top: scale(14),
  },
  eyeIcon: {
    width: scale(18),
    height: scale(18),
    tintColor: theme.muted,
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: scale(14),
    marginTop: scale(2),
    marginBottom: scale(16),
    flexWrap: 'wrap',
  },
  linkText: {
    color: theme.navy,
    fontSize: scale(12),
    fontWeight: '800',
  },
  mutedLink: {
    color: theme.muted,
    fontSize: scale(12),
    fontWeight: '700',
    textAlign: 'center',
  },
  feedback: {
    marginBottom: scale(14),
    paddingHorizontal: scale(14),
    paddingVertical: scale(12),
    borderRadius: scale(14),
    borderWidth: 1,
    borderColor: 'rgba(185, 20, 39, 0.16)',
    backgroundColor: 'rgba(185, 20, 39, 0.07)',
  },
  feedbackSuccess: {
    borderColor: 'rgba(13, 71, 161, 0.18)',
    backgroundColor: 'rgba(13, 71, 161, 0.07)',
  },
  feedbackText: {
    color: theme.red,
    fontSize: scale(12),
    fontWeight: '800',
    lineHeight: scale(16),
  },
  feedbackTextSuccess: {
    color: theme.navy,
  },
  primaryBtnWrap: {
    borderRadius: scale(18),
    overflow: 'hidden',
    shadowColor: 'rgba(7, 27, 52, 0.24)',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 1,
    shadowRadius: 28,
    elevation: 8,
    marginTop: scale(4),
  },
  primaryBtn: {
    height: scale(50),
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: scale(16),
    fontWeight: '800',
  },
  finePrint: {
    marginTop: scale(36),
    color: '#7a8491',
    fontSize: scale(11),
    fontWeight: '600',
    lineHeight: scale(16),
    textAlign: 'center',
  },
  stepIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scale(18),
    paddingHorizontal: scale(12),
  },
  stepDot: {
    width: scale(10),
    height: scale(10),
    borderRadius: scale(5),
    backgroundColor: theme.line,
    borderWidth: 2,
    borderColor: theme.line,
  },
  stepDotActive: {
    backgroundColor: theme.navy,
    borderColor: theme.navy,
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: theme.line,
    marginHorizontal: scale(6),
  },
  stepLineActive: {
    backgroundColor: theme.navy,
  },
  strengthBox: {
    marginTop: scale(8),
    paddingVertical: scale(10),
    paddingHorizontal: scale(12),
    backgroundColor: theme.cream,
    borderRadius: scale(12),
    borderWidth: 1,
    borderColor: theme.line,
  },
  strengthText: {
    fontSize: scale(11),
    color: theme.muted,
    fontWeight: '600',
    marginVertical: scale(2),
  },
  strengthTextDone: {
    color: theme.success,
    fontWeight: '800',
  },
  strengthTextError: {
    color: theme.red,
    fontWeight: '800',
  },
  emailHighlight: {
    color: theme.navy,
    fontWeight: '800',
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(8),
  },
  checkbox: {
    width: scale(17),
    height: scale(17),
    borderRadius: scale(4),
    borderWidth: 1.5,
    borderColor: theme.navy,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  checkboxChecked: {
    backgroundColor: theme.navy,
  },
  checkmark: {
    color: '#fff',
    fontSize: scale(11),
    fontWeight: '800',
    lineHeight: scale(12),
  },
  rememberText: {
    color: theme.muted,
    fontSize: scale(12),
    fontWeight: '700',
  },
});
